# Generated by Django 5.0.6 on 2024-07-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=255)),
                ('items', models.TextField()),
                ('precios', models.TextField()),
                ('cantidades', models.TextField()),
                ('fecha_actual', models.CharField(max_length=40)),
                ('fecha_despacho', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('id_tipo', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=45, null=True)),
                ('garantia', models.IntegerField()),
                ('modelo', models.CharField(max_length=105)),
                ('img', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductosVista',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('id_tipo_producto', models.IntegerField()),
                ('tipo', models.CharField(max_length=105)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('color', models.CharField(max_length=45)),
                ('garantia', models.IntegerField()),
                ('modelo', models.CharField(max_length=105)),
                ('img', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=105)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
